
platform :ios, '10.0'

target 'easypass' do
  use_frameworks!

  source 'https://github.com/CocoaPods/Specs.git'

  pod 'SnapKit', '~> 3.0'
  pod 'RealmSwift', '~> 2.0'
  pod 'PFColorHash', '~> 2.0'
  pod 'UIHelper', :git => 'git@github.com:pkg4swift/UIHelper.git', :branch => 'master'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
